# Copyright 2012 - Matias P. Brutti - matiasbrutti@gmail.com
# # All rights reserved.
#

include $(GOROOT)/src/Make.inc

 TARG=github.com/FreedomCoder/nmap

 GOFILES=\
		nmap.go\

include $(GOROOT)/src/Make.pkg